---
- :data:
    :name: meta_data
    :type: mixin
    :properties:
      :date_created:
        :label: Erstellungsdatum
        :type: datetime
        :storage_location: value
        :ui:
         :edit:
           disabled: true
         :show:
           :type: date
      :date_modified:
        :label: Änderungsdatum
        :type: datetime
        :storage_location: value
        :ui:
         :edit:
           disabled: true
         :show:
           :type: date
      :date_deleted:
        :label: Löschdatum
        :type: datetime
        :storage_location: value
        :ui:
         :edit:
           disabled: true
         :show:
           :type: date
